-- =============================================================================
-- Workers
--   * a worker has a job title; the owner sees the avatar and name of the
--     accounts that work for them
--   * invites: the database picks the code and the expiry, the server accepts
--   * one account works for at most one owner
--   * reward rules have one checked shape; the owner's editor keeps a draft tree
--   * earnings are generated by the database from four triggers, always pending
--   * approval and payment stamps are the database's; paid is final
--   * the work timer has a status read like the prospecting timer
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Workers: job title, name length, one employer per account
-- -----------------------------------------------------------------------------

alter table public.workers
  add column job_title text,
  add constraint workers_job_title_length check (job_title is null or char_length(job_title) between 1 and 60),
  add constraint workers_name_length check (char_length(name) between 1 and 80),
  add constraint workers_email_length check (email is null or char_length(email) <= 254);

create unique index workers_one_employer_idx on public.workers (user_id) where user_id is not null;

-- The owner sees the profile (name, avatar) of accounts that work for them.
create policy "profiles_select_my_workers" on public.profiles for select to authenticated
  using (id in (
    select w.user_id from public.workers w
    where w.owner_id = (select auth.uid()) and w.user_id is not null
  ));

-- -----------------------------------------------------------------------------
-- Permissions: editing includes viewing
-- -----------------------------------------------------------------------------

alter table public.worker_permissions
  add constraint worker_permissions_edit_needs_view check (not can_edit or can_view);

-- -----------------------------------------------------------------------------
-- Invites: code and expiry come from the database, acceptance from the server
-- -----------------------------------------------------------------------------

create or replace function public.new_invite_code()
returns text
language sql
volatile
set search_path = ''
as $$
  select substr(replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''), 1, 20);
$$;

create or replace function public.worker_invites_guard()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if not public.is_client_request() then
    return new;
  end if;
  if tg_op = 'INSERT' then
    if new.accepted_at is not null or new.accepted_by is not null then
      raise exception 'invite_acceptance_is_server_only' using errcode = 'insufficient_privilege';
    end if;
    new.code := public.new_invite_code();
    new.expires_at := now() + interval '7 days';
    return new;
  end if;
  if new.accepted_at is distinct from old.accepted_at
     or new.accepted_by is distinct from old.accepted_by then
    raise exception 'invite_acceptance_is_server_only' using errcode = 'insufficient_privilege';
  end if;
  if new.code is distinct from old.code or new.expires_at is distinct from old.expires_at then
    raise exception 'invite_code_is_server_only' using errcode = 'insufficient_privilege';
  end if;
  return new;
end;
$$;

-- Called by the registration with the service role only: binds the new account
-- to the worker, activates it and marks the invite used, all or nothing.
create or replace function public.accept_worker_invite(_code text, _user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  _invite public.worker_invites;
begin
  select * into _invite from public.worker_invites where code = _code for update;
  if _invite.id is null or _invite.accepted_at is not null or _invite.expires_at < now() then
    raise exception 'invite_invalid' using errcode = 'check_violation';
  end if;
  if exists (select 1 from public.workers where user_id = _user_id) then
    raise exception 'already_worker' using errcode = 'check_violation';
  end if;

  update public.workers
  set user_id = _user_id, status = 'active'
  where id = _invite.worker_id and user_id is null;
  if not found then
    raise exception 'invite_invalid' using errcode = 'check_violation';
  end if;

  update public.worker_invites
  set accepted_at = now(), accepted_by = _user_id
  where id = _invite.id;
  return _invite.worker_id;
end;
$$;
revoke execute on function public.accept_worker_invite(text, uuid) from public, anon, authenticated;
grant execute on function public.accept_worker_invite(text, uuid) to service_role;

-- -----------------------------------------------------------------------------
-- Reward rules: one checked shape
--   { trigger, kind, amount, conditions: { minDealValue?, onlyBeforeDue?, maxPerMonth? } }
--   hourly only for hour_worked, percent only for deal_won (max 100)
-- -----------------------------------------------------------------------------

create type public.reward_trigger as enum ('task_completed', 'meeting_booked', 'deal_won', 'hour_worked');

create or replace function public.reward_rule_is_valid(_rule jsonb)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare
  _trigger text;
  _kind text;
  _amount numeric;
  _conditions jsonb;
  _key text;
begin
  if _rule is null or jsonb_typeof(_rule) <> 'object' then
    return false;
  end if;
  _trigger := _rule ->> 'trigger';
  _kind := _rule ->> 'kind';
  if _trigger is null or _trigger not in ('task_completed', 'meeting_booked', 'deal_won', 'hour_worked') then
    return false;
  end if;
  if _kind is null or _kind not in ('fixed', 'percent', 'hourly') then
    return false;
  end if;
  if (_kind = 'hourly') <> (_trigger = 'hour_worked') then
    return false;
  end if;
  if _kind = 'percent' and _trigger <> 'deal_won' then
    return false;
  end if;
  if jsonb_typeof(_rule -> 'amount') is distinct from 'number' then
    return false;
  end if;
  _amount := (_rule ->> 'amount')::numeric;
  if _amount <= 0 or _amount > 10000000 or (_kind = 'percent' and _amount > 100) then
    return false;
  end if;

  _conditions := coalesce(_rule -> 'conditions', '{}'::jsonb);
  if jsonb_typeof(_conditions) <> 'object' then
    return false;
  end if;
  for _key in select jsonb_object_keys(_conditions) loop
    if _key not in ('minDealValue', 'onlyBeforeDue', 'maxPerMonth') then
      return false;
    end if;
  end loop;
  -- Nested checks: a value is only cast once its JSON type is known.
  if _conditions ? 'minDealValue' then
    if _trigger <> 'deal_won' or jsonb_typeof(_conditions -> 'minDealValue') <> 'number' then
      return false;
    end if;
    if (_conditions ->> 'minDealValue')::numeric < 0 then
      return false;
    end if;
  end if;
  if _conditions ? 'onlyBeforeDue' then
    if _trigger <> 'task_completed' or jsonb_typeof(_conditions -> 'onlyBeforeDue') <> 'boolean' then
      return false;
    end if;
  end if;
  if _conditions ? 'maxPerMonth' then
    if jsonb_typeof(_conditions -> 'maxPerMonth') <> 'number'
       or (_conditions ->> 'maxPerMonth') !~ '^[1-9][0-9]{0,5}$' then
      return false;
    end if;
  end if;
  return true;
end;
$$;

-- Existing rows (none in use yet) are not re-checked; every new or changed rule is.
alter table public.reward_rules
  add constraint reward_rules_shape check (public.reward_rule_is_valid(rules)) not valid,
  add constraint reward_rules_name_length check (char_length(name) between 1 and 120);

-- Confirming a new set replaces the active one. Old rules stay (inactive) so
-- earnings keep pointing at the rule that produced them.
create or replace function public.replace_reward_rules(_rules jsonb)
returns integer
language plpgsql
set search_path = ''
as $$
declare
  _uid uuid := auth.uid();
  _count integer;
begin
  if _uid is null then
    raise exception 'not_authenticated' using errcode = 'insufficient_privilege';
  end if;
  if jsonb_typeof(_rules) <> 'array' or jsonb_array_length(_rules) > 100 then
    raise exception 'invalid_rules' using errcode = 'check_violation';
  end if;

  update public.reward_rules set is_active = false where owner_id = _uid and is_active;

  insert into public.reward_rules (owner_id, worker_id, name, rules, is_active)
  select _uid, nullif(item ->> 'workerId', '')::uuid, item ->> 'name', item -> 'rule', true
  from jsonb_array_elements(_rules) as item;
  get diagnostics _count = row_count;
  return _count;
end;
$$;

-- -----------------------------------------------------------------------------
-- Reward drafts: the tree the owner edits before it becomes rules
-- -----------------------------------------------------------------------------

create table public.reward_drafts (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null unique references auth.users (id) on delete cascade,
  tree jsonb not null default '{"branches": []}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(tree) = 'object' and pg_column_size(tree) < 65536)
);
create trigger set_updated_at before update on public.reward_drafts
  for each row execute function public.set_updated_at();

alter table public.reward_drafts enable row level security;
create policy "reward_drafts_owner_all" on public.reward_drafts for all to authenticated
  using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);

-- -----------------------------------------------------------------------------
-- Earnings: where they came from, and stamps the client cannot write
-- -----------------------------------------------------------------------------

alter table public.worker_earnings
  add column source public.reward_trigger,
  add column source_ref uuid,
  add column basis numeric(14, 2);

-- One earning per rule and event: a task done twice or a deal won again pays once.
create unique index worker_earnings_rule_source_idx
  on public.worker_earnings (reward_rule_id, source, source_ref)
  where reward_rule_id is not null and source_ref is not null;
create index worker_earnings_source_ref_idx on public.worker_earnings (source_ref) where source_ref is not null;
create index worker_earnings_worker_created_idx on public.worker_earnings (worker_id, created_at desc);

create or replace function public.worker_earnings_guard()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if public.is_client_request() then
    if tg_op = 'DELETE' then
      if old.status = 'paid' then
        raise exception 'earning_paid_is_final' using errcode = 'insufficient_privilege';
      end if;
      return old;
    end if;
    if tg_op = 'INSERT' then
      if new.status = 'paid' or new.payment_id is not null or new.source is not null
         or new.source_ref is not null or new.basis is not null then
        raise exception 'earning_source_is_server_only' using errcode = 'insufficient_privilege';
      end if;
    else
      if old.status = 'paid' then
        raise exception 'earning_paid_is_final' using errcode = 'insufficient_privilege';
      end if;
      if new.status = 'paid'
         or new.payment_id is distinct from old.payment_id
         or new.source is distinct from old.source
         or new.source_ref is distinct from old.source_ref
         or new.basis is distinct from old.basis
         or new.reward_rule_id is distinct from old.reward_rule_id
         or new.worker_task_id is distinct from old.worker_task_id
         or new.work_session_id is distinct from old.work_session_id then
        raise exception 'earning_source_is_server_only' using errcode = 'insufficient_privilege';
      end if;
    end if;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  -- Stamps follow the status.
  if new.status = 'pending' then
    new.approved_at := null;
    new.paid_at := null;
    new.payment_id := null;
  elsif new.status = 'approved' then
    new.paid_at := null;
    new.payment_id := null;
    if tg_op = 'INSERT' or old.status <> 'approved' then
      new.approved_at := now();
    else
      new.approved_at := old.approved_at;
    end if;
  else
    new.approved_at := coalesce(case when tg_op = 'UPDATE' then old.approved_at end, now());
    new.paid_at := coalesce(new.paid_at, now());
  end if;
  return new;
end;
$$;
create trigger worker_earnings_guard
  before insert or update or delete on public.worker_earnings
  for each row execute function public.worker_earnings_guard();

-- -----------------------------------------------------------------------------
-- Generating earnings
-- -----------------------------------------------------------------------------

-- Applies the owner's active rules for one event of one worker. Every earning
-- starts pending; the owner approves it. Returns how many were created.
create or replace function public.grant_worker_rewards(
  _worker_id uuid,
  _trigger public.reward_trigger,
  _source_ref uuid,
  _basis numeric,
  _on_time boolean,
  _description text,
  _task_id uuid,
  _session_id uuid
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  _worker public.workers;
  _tz text;
  _currency text;
  _month_start timestamptz;
  _rule public.reward_rules;
  _kind text;
  _rate numeric;
  _amount numeric;
  _conditions jsonb;
  _created integer := 0;
  _inserted integer;
begin
  select * into _worker from public.workers where id = _worker_id and status = 'active';
  if _worker.id is null then
    return 0;
  end if;

  select s.timezone, s.currency into _tz, _currency
  from public.user_settings s where s.user_id = _worker.owner_id;
  _tz := coalesce(_tz, 'UTC');
  _currency := coalesce(_currency, 'CZK');
  _month_start := date_trunc('month', now() at time zone _tz) at time zone _tz;

  for _rule in
    select r.* from public.reward_rules r
    where r.owner_id = _worker.owner_id
      and r.is_active
      and (r.worker_id is null or r.worker_id = _worker.id)
      and r.rules ->> 'trigger' = _trigger::text
      and public.reward_rule_is_valid(r.rules)
    order by r.created_at, r.id
  loop
    _kind := _rule.rules ->> 'kind';
    _rate := (_rule.rules ->> 'amount')::numeric;
    _conditions := coalesce(_rule.rules -> 'conditions', '{}'::jsonb);

    if _kind = 'fixed' then
      _amount := _rate;
    elsif _kind = 'percent' then
      _amount := round(coalesce(_basis, 0) * _rate / 100, 2);
    else
      _amount := round(coalesce(_basis, 0) * _rate, 2);
    end if;
    continue when _amount is null or _amount <= 0;

    continue when _conditions ? 'minDealValue'
      and coalesce(_basis, 0) < (_conditions ->> 'minDealValue')::numeric;
    continue when coalesce((_conditions ->> 'onlyBeforeDue')::boolean, false)
      and not coalesce(_on_time, true);
    continue when _conditions ? 'maxPerMonth' and (
      select count(*) from public.worker_earnings e
      where e.worker_id = _worker.id and e.reward_rule_id = _rule.id and e.created_at >= _month_start
    ) >= (_conditions ->> 'maxPerMonth')::integer;

    insert into public.worker_earnings (
      owner_id, worker_id, amount, currency, description, status,
      reward_rule_id, worker_task_id, work_session_id, source, source_ref, basis
    ) values (
      _worker.owner_id, _worker.id, _amount, _currency, left(_description, 200), 'pending',
      _rule.id, _task_id, _session_id, _trigger, _source_ref,
      case when _kind = 'fixed' then null else _basis end
    )
    on conflict (reward_rule_id, source, source_ref)
      where reward_rule_id is not null and source_ref is not null
      do nothing;
    get diagnostics _inserted = row_count;
    _created := _created + _inserted;
  end loop;
  return _created;
end;
$$;
revoke execute on function public.grant_worker_rewards(uuid, public.reward_trigger, uuid, numeric, boolean, text, uuid, uuid)
  from public, anon, authenticated;

-- An event undone (task reopened, deal no longer won) takes back what was not approved yet.
create or replace function public.revoke_pending_rewards(_trigger public.reward_trigger, _source_ref uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  delete from public.worker_earnings
  where source = _trigger and source_ref = _source_ref and status = 'pending';
$$;
revoke execute on function public.revoke_pending_rewards(public.reward_trigger, uuid)
  from public, anon, authenticated;

-- 1. A task the owner assigned is done.
create or replace function public.worker_tasks_rewards()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  _tz text;
begin
  if new.status = 'done' and old.status <> 'done' then
    select s.timezone into _tz from public.user_settings s where s.user_id = new.owner_id;
    perform public.grant_worker_rewards(
      new.worker_id, 'task_completed', new.id, null,
      new.due_date is null
        or (coalesce(new.completed_at, now()) at time zone coalesce(_tz, 'UTC'))::date <= new.due_date,
      new.title, new.id, null
    );
  elsif old.status = 'done' and new.status <> 'done' then
    perform public.revoke_pending_rewards('task_completed', new.id);
  end if;
  return null;
end;
$$;
create trigger worker_tasks_rewards
  after update of status on public.worker_tasks
  for each row execute function public.worker_tasks_rewards();

-- 2. A work session is closed (paused, or cut as idle): hours worked.
create or replace function public.work_sessions_rewards()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  _hours numeric;
begin
  if old.ended_at is null and new.ended_at is not null then
    _hours := extract(epoch from new.ended_at - new.started_at) / 3600.0;
    if _hours > 0 then
      perform public.grant_worker_rewards(
        new.worker_id, 'hour_worked', new.id, round(_hours, 2), null, null, null, new.id
      );
    end if;
  end if;
  return null;
end;
$$;
create trigger work_sessions_rewards
  after update of ended_at on public.work_sessions
  for each row execute function public.work_sessions_rewards();

-- 3. A worker books a meeting: moves a contact of their own into "Meeting scheduled".
create or replace function public.contact_moves_rewards()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  _worker_id uuid;
  _name text;
begin
  select w.id into _worker_id from public.workers w
  where w.user_id = new.user_id and w.status = 'active';
  if _worker_id is null then
    return null;
  end if;
  if not exists (
    select 1 from public.contact_tables t
    where t.id = new.to_table_id and t.system_key = 'meeting_scheduled'
  ) then
    return null;
  end if;

  select coalesce(nullif(c.company_name, ''), nullif(trim(concat_ws(' ', c.first_name, c.last_name)), ''))
  into _name
  from public.contacts c where c.id = new.contact_id;

  -- Once per contact: moving it out and back does not pay again.
  perform public.grant_worker_rewards(
    _worker_id, 'meeting_booked', new.contact_id, null, null, _name, null, null
  );
  return null;
end;
$$;
create trigger contact_moves_rewards
  after insert on public.contact_table_moves
  for each row execute function public.contact_moves_rewards();

-- 4. A worker wins a deal of their own.
create or replace function public.deals_rewards()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  _worker_id uuid;
begin
  select w.id into _worker_id from public.workers w
  where w.user_id = new.user_id and w.status = 'active';
  if _worker_id is null then
    return null;
  end if;

  if new.won_at is not null and (tg_op = 'INSERT' or old.won_at is null) then
    perform public.grant_worker_rewards(
      _worker_id, 'deal_won', new.id, new.value, null, new.title, null, null
    );
  elsif tg_op = 'UPDATE' and old.won_at is not null and new.won_at is null then
    perform public.revoke_pending_rewards('deal_won', new.id);
  end if;
  return null;
end;
$$;
-- won_at is set by a BEFORE trigger, so the column is not in the UPDATE list: no "of won_at".
create trigger deals_rewards
  after insert or update on public.deals
  for each row execute function public.deals_rewards();

-- -----------------------------------------------------------------------------
-- Payments: recorded by the owner, settling approved earnings oldest first
-- -----------------------------------------------------------------------------

create or replace function public.record_worker_payment(
  _worker_id uuid,
  _amount numeric,
  _paid_at timestamptz,
  _note text
)
returns public.worker_payments
language plpgsql
security definer
set search_path = ''
as $$
declare
  _owner uuid := auth.uid();
  _currency text;
  _payment public.worker_payments;
  _credit numeric;
  _earning record;
begin
  if _owner is null or not exists (
    select 1 from public.workers where id = _worker_id and owner_id = _owner
  ) then
    raise exception 'worker_not_found' using errcode = 'no_data_found';
  end if;
  if _amount is null or _amount <= 0 or _amount > 100000000 then
    raise exception 'amount_invalid' using errcode = 'check_violation';
  end if;
  if _note is not null and char_length(_note) > 200 then
    raise exception 'note_too_long' using errcode = 'check_violation';
  end if;

  select currency into _currency from public.user_settings where user_id = _owner;

  insert into public.worker_payments (owner_id, worker_id, amount, currency, paid_at, note)
  values (_owner, _worker_id, round(_amount, 2), coalesce(_currency, 'CZK'),
          least(coalesce(_paid_at, now()), now()), nullif(trim(_note), ''))
  returning * into _payment;

  -- Everything paid so far minus what is already marked paid covers approved earnings in order.
  _credit :=
    coalesce((select sum(amount) from public.worker_payments where worker_id = _worker_id), 0)
    - coalesce((select sum(amount) from public.worker_earnings
                where worker_id = _worker_id and status = 'paid'), 0);

  for _earning in
    select id, amount from public.worker_earnings
    where worker_id = _worker_id and status = 'approved'
    order by approved_at, created_at, amount, id
  loop
    -- One that does not fit waits for the next payment; smaller later ones may still fit.
    continue when _earning.amount > _credit;
    update public.worker_earnings
    set status = 'paid', paid_at = _payment.paid_at, payment_id = _payment.id
    where id = _earning.id;
    _credit := _credit - _earning.amount;
  end loop;

  return _payment;
end;
$$;

-- Earned (approved or paid), pending, paid out and still owed. RLS decides who sees it.
create or replace function public.worker_balance(_worker_id uuid)
returns table (earned numeric, pending numeric, paid_out numeric, owed numeric)
language sql
stable
set search_path = ''
as $$
  with e as (
    select
      coalesce(sum(amount) filter (where status in ('approved', 'paid')), 0) as earned,
      coalesce(sum(amount) filter (where status = 'pending'), 0) as pending
    from public.worker_earnings where worker_id = _worker_id
  ), p as (
    select coalesce(sum(amount), 0) as paid_out
    from public.worker_payments where worker_id = _worker_id
  )
  select e.earned, e.pending, p.paid_out, greatest(e.earned - p.paid_out, 0)
  from e, p;
$$;

-- -----------------------------------------------------------------------------
-- Work time
-- -----------------------------------------------------------------------------

-- Last activity of a session: the worker touching their tasks since it started.
create or replace function public.work_session_last_activity_at(_session public.work_sessions)
returns timestamptz
language sql
stable
set search_path = ''
as $$
  select greatest(
    _session.started_at,
    coalesce((
      select max(updated_at) from public.worker_tasks
      where worker_id = _session.worker_id and updated_at >= _session.started_at
    ), _session.started_at)
  );
$$;

-- Seconds worked between two instants, idle rule applied; RLS decides whose sessions count.
create or replace function public.work_seconds_between(_worker_id uuid, _from timestamptz, _to timestamptz)
returns integer
language sql
stable
set search_path = ''
as $$
  select coalesce(sum(
    extract(epoch from least(public.work_session_effective_end(s), _to) - greatest(s.started_at, _from))
  ), 0)::integer
  from public.work_sessions s
  where s.worker_id = _worker_id
    and s.started_at < _to
    and public.work_session_effective_end(s) > _from;
$$;

-- Closes sessions whose idle end has passed, for the owner's workers or one's own
-- worker record, so hours worked become earnings even if nobody pressed pause.
create or replace function public.settle_idle_work_sessions()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  _uid uuid := auth.uid();
  _session public.work_sessions;
  _effective timestamptz;
  _closed integer := 0;
begin
  if _uid is null then
    raise exception 'not_authenticated' using errcode = 'insufficient_privilege';
  end if;
  for _session in
    select s.* from public.work_sessions s
    join public.workers w on w.id = s.worker_id
    where s.ended_at is null and (w.owner_id = _uid or w.user_id = _uid)
  loop
    _effective := public.work_session_effective_end(_session);
    if _effective < now() then
      update public.work_sessions set ended_at = _effective, end_reason = 'idle'
      where id = _session.id;
      _closed := _closed + 1;
    end if;
  end loop;
  return _closed;
end;
$$;

-- The worker's own timer: one read settles an idle session and reports it once.
create or replace function public.work_status(_timezone text)
returns table (
  worker_id uuid,
  running boolean,
  session_started_at timestamptz,
  idle_deadline timestamptz,
  today_seconds integer,
  month_seconds integer,
  server_now timestamptz,
  idle_closed_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  _uid uuid := auth.uid();
  _worker uuid;
  _open public.work_sessions;
  _effective timestamptz;
  _closed timestamptz;
  _day_start timestamptz;
  _month_start timestamptz;
begin
  if _uid is null then
    raise exception 'not_authenticated' using errcode = 'insufficient_privilege';
  end if;
  select w.id into _worker from public.workers w where w.user_id = _uid and w.status = 'active';
  if _worker is null then
    raise exception 'worker_not_found' using errcode = 'no_data_found';
  end if;

  select s.* into _open from public.work_sessions s where s.worker_id = _worker and s.ended_at is null;
  if _open.id is not null then
    _effective := public.work_session_effective_end(_open);
    if _effective < now() then
      update public.work_sessions s set ended_at = _effective, end_reason = 'idle'
      where s.id = _open.id;
      _closed := _effective;
      _open := null;
    end if;
  end if;

  _day_start := date_trunc('day', now() at time zone _timezone) at time zone _timezone;
  _month_start := date_trunc('month', now() at time zone _timezone) at time zone _timezone;

  return query
  select
    _worker,
    _open.id is not null,
    _open.started_at,
    case when _open.id is not null
      then public.work_session_last_activity_at(_open) + public.timer_idle_interval()
    end,
    public.work_seconds_between(_worker, _day_start, _day_start + interval '1 day'),
    public.work_seconds_between(_worker, _month_start, now() + interval '1 day'),
    now(),
    _closed;
end;
$$;

-- Recent sessions of a worker with their effective end; RLS decides who sees them.
create or replace function public.worker_sessions(_worker_id uuid, _limit integer, _before timestamptz)
returns table (id uuid, started_at timestamptz, effective_end timestamptz, end_reason public.session_end_reason, running boolean)
language sql
stable
set search_path = ''
as $$
  select s.id, s.started_at, public.work_session_effective_end(s), s.end_reason,
         s.ended_at is null and public.work_session_effective_end(s) >= now()
  from public.work_sessions s
  where s.worker_id = _worker_id
    and (_before is null or s.started_at < _before)
  order by s.started_at desc
  limit least(greatest(coalesce(_limit, 20), 1), 50);
$$;

-- One month for the cards: time worked, earned (approved or paid), all pending,
-- and the month's tasks (due in it, done in it, or created in it without a due date).
create or replace function public.worker_month_stats(_month_start date, _timezone text)
returns table (
  worker_id uuid,
  work_seconds integer,
  earned numeric,
  pending_amount numeric,
  pending_count integer,
  tasks_total integer,
  tasks_done integer
)
language sql
stable
set search_path = ''
as $$
  with bounds as (
    select
      (_month_start::timestamp at time zone _timezone) as from_at,
      ((_month_start + interval '1 month')::timestamp at time zone _timezone) as to_at,
      _month_start as from_day,
      (_month_start + interval '1 month')::date as to_day
  ),
  mine as (
    select w.id from public.workers w
    where w.owner_id = (select auth.uid()) or w.user_id = (select auth.uid())
  )
  select
    m.id,
    public.work_seconds_between(m.id, b.from_at, b.to_at),
    coalesce((select sum(e.amount) from public.worker_earnings e
              where e.worker_id = m.id and e.status in ('approved', 'paid')
                and e.created_at >= b.from_at and e.created_at < b.to_at), 0),
    coalesce((select sum(e.amount) from public.worker_earnings e
              where e.worker_id = m.id and e.status = 'pending'), 0),
    (select count(*)::integer from public.worker_earnings e
     where e.worker_id = m.id and e.status = 'pending'),
    (select count(*)::integer from public.worker_tasks t
     where t.worker_id = m.id and (
       (t.due_date >= b.from_day and t.due_date < b.to_day)
       or (t.completed_at >= b.from_at and t.completed_at < b.to_at)
       or (t.due_date is null and t.created_at >= b.from_at and t.created_at < b.to_at))),
    (select count(*)::integer from public.worker_tasks t
     where t.worker_id = m.id and t.status = 'done' and (
       (t.due_date >= b.from_day and t.due_date < b.to_day)
       or (t.completed_at >= b.from_at and t.completed_at < b.to_at)
       or (t.due_date is null and t.created_at >= b.from_at and t.created_at < b.to_at)))
  from mine m, bounds b;
$$;

-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------

revoke execute on function
  public.new_invite_code(),
  public.reward_rule_is_valid(jsonb),
  public.replace_reward_rules(jsonb),
  public.worker_earnings_guard(),
  public.worker_tasks_rewards(),
  public.work_sessions_rewards(),
  public.contact_moves_rewards(),
  public.deals_rewards(),
  public.record_worker_payment(uuid, numeric, timestamptz, text),
  public.worker_balance(uuid),
  public.work_session_last_activity_at(public.work_sessions),
  public.work_seconds_between(uuid, timestamptz, timestamptz),
  public.settle_idle_work_sessions(),
  public.work_status(text),
  public.worker_sessions(uuid, integer, timestamptz),
  public.worker_month_stats(date, text)
from public, anon;

grant execute on function
  public.replace_reward_rules(jsonb),
  public.record_worker_payment(uuid, numeric, timestamptz, text),
  public.worker_balance(uuid),
  public.work_seconds_between(uuid, timestamptz, timestamptz),
  public.settle_idle_work_sessions(),
  public.work_status(text),
  public.worker_sessions(uuid, integer, timestamptz),
  public.worker_month_stats(date, text)
to authenticated;
